### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by ikbenjoeri** [LordGaav/proxmox-deploy#11]
Hello,

If run the next command
proxmox-deploy --proxmox-host kvm01 --cloud-images-dir /var/lib/vz/template/cloud-init/
I get this error

Traceback (most recent call last):
  File "/usr/local/bin/proxmox-deploy", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/proxmoxdeploy/cli.py", line 93, in main
    (proxmox, cloudinit) = interact_with_user(args, api)
  File "/usr/local/lib/python2.7/dist-packages/proxmoxdeploy/cli.py", line 77, in interact_with_user
    proxmox_answers = ask_proxmox_questions(api)
  File "/usr/local/lib/python2.7/dist-packages/proxmoxdeploy/proxmox.py", line 50, in ask_proxmox_questions
    available_nodes = proxmox.get_nodes()
  File "/usr/local/lib/python2.7/dist-packages/proxmoxdeploy/proxmox.py", line 121, in get_nodes
    return [_node['node'] for _node in self.client.nodes.get()]
  File "/usr/local/lib/python2.7/dist-packages/proxmoxer/core.py", line 84, in get
    return self(args)._request("GET", params=params)
  File "/usr/local/lib/python2.7/dist-packages/proxmoxer/core.py", line 79, in _request
    raise ResourceException("{0} {1}".format(resp.status_code, httplib.responses[resp.status_code]))
proxmoxer.core.ResourceException: 500 Internal Server Error

**Comment by LordGaav** [comment]
The error is thrown by the Proxmox API when trying to determine what nodes are available. I suggest you check your Proxmox logs to determine what went wrong.
